version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app_web
    command: >
      sh -c "python manage.py migrate &&
              daphne -b 0.0.0.0 -p 8010 core.asgi:application"
    ports:
      - "8010:8010"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=True
      # Agar .env fayl ishlatilsa, quyidagicha yozing:
      # env_file:
      #   - .env
#     depends_on:
#       - db

#   db:
#     image: postgres:14
#     container_name: django_app_db
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: django_user
#       POSTGRES_PASSWORD: django_password
#       POSTGRES_DB: django_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
