# Generated by Django 5.2 on 2025-04-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_app.device')),
            ],
        ),
    ]
