# Generated by Django 5.2 on 2025-05-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0002_device_limit_mtt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtt',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
