# Generated by Django 5.2 on 2025-06-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0004_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('manafacturer', models.CharField(max_length=250)),
                ('device_id', models.CharField(max_length=250, unique=True)),
                ('device_name', models.CharField(max_length=250)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_app.token')),
            ],
            options={
                'verbose_name': 'Phone Device',
                'verbose_name_plural': 'Phone Devices',
                'ordering': ['-token__created_at'],
                'unique_together': {('token', 'device_id')},
            },
        ),
    ]
