# Generated by Django 5.2 on 2025-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0005_phonedevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayIntegrityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Play Integrity Token',
                'verbose_name_plural': 'Play Integrity Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
