# Generated by Django 5.2 on 2025-07-16 11:58

from django.db import migrations, models
from uuid import uuid4


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0006_playintegritytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedevice',
            name='base_device_id',
            field=models.CharField(default=uuid4(), max_length=250),
            preserve_default=False,
        ),
    ]
